"""Expand following feature

Revision ID: 40321ec7a281
Revises: 9d1aaaed7ecd
Create Date: 2016-10-27 11:28:55.924300

"""

# revision identifiers, used by Alembic.
revision = '40321ec7a281'
down_revision = '9d1aaaed7ecd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
