"""Test migrate

Revision ID: 43ed62db1039
Revises: 28d0877cd573
Create Date: 2016-10-26 21:37:19.944018

"""

# revision identifiers, used by Alembic.
revision = '43ed62db1039'
down_revision = '28d0877cd573'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
