"""Add creation of fake posts and users

Revision ID: 57678b4d62f8
Revises: 5a4b347be9bb
Create Date: 2016-10-26 23:10:29.229960

"""

# revision identifiers, used by Alembic.
revision = '57678b4d62f8'
down_revision = '5a4b347be9bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
