"""api 1.0

Revision ID: c96deb781822
Revises: e4170be1fb43
Create Date: 2016-10-28 00:18:44.190356

"""

# revision identifiers, used by Alembic.
revision = 'c96deb781822'
down_revision = 'e4170be1fb43'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
