"""Add rich text body text

Revision ID: e457dd48220d
Revises: 57678b4d62f8
Create Date: 2016-10-26 23:54:28.716277

"""

# revision identifiers, used by Alembic.
revision = 'e457dd48220d'
down_revision = '57678b4d62f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
