"""Add avatar hash

Revision ID: e8b5d5006c03
Revises: 43ed62db1039
Create Date: 2016-10-26 22:24:47.444173

"""

# revision identifiers, used by Alembic.
revision = 'e8b5d5006c03'
down_revision = '43ed62db1039'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
