# Generated by Django 3.2.3 on 2021-05-25 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('source', models.CharField(max_length=100)),
                ('cc_from', models.CharField(max_length=10)),
                ('cc_to', models.CharField(max_length=10)),
                ('rate', models.FloatField()),
            ],
        ),
    ]
