# Generated by Django 3.2.3 on 2021-05-25 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('source', models.CharField(max_length=1000)),
                ('payload', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='CurrencyRate',
        ),
    ]
