# Generated by Django 3.2.3 on 2021-05-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210525_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyraterequest',
            name='source',
            field=models.CharField(max_length=100),
        ),
    ]
